[[redirects]]
from = "/"
to = "https://hensin.space"
status = 301
force = true

[[redirects]]
from = "/xp-ge-craft"
to = "https://hensin.space"
status = 301
force = true

[[redirects]]
from = "/xp-ge-craft/*"
to = "https://hensin.space"
status = 301
force = true
